[2023-07-20T14:14:03.107+0000] {taskinstance.py:1097} INFO - Dependencies not met for <TaskInstance: my-first-dag.extract scheduled__2023-07-17T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-07-20T14:14:03.107832+00:00 and task will be retried at 2023-07-20T14:17:33.486915+00:00.
[2023-07-20T14:14:03.294+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-07-20T14:17:34.521+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my-first-dag.extract scheduled__2023-07-17T00:00:00+00:00 [queued]>
[2023-07-20T14:17:34.528+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my-first-dag.extract scheduled__2023-07-17T00:00:00+00:00 [queued]>
[2023-07-20T14:17:34.528+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-20T14:17:34.537+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract> on 2023-07-17 00:00:00+00:00
[2023-07-20T14:17:34.541+0000] {standard_task_runner.py:57} INFO - Started process 126 to run task
[2023-07-20T14:17:34.545+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my-first-dag', 'extract', 'scheduled__2023-07-17T00:00:00+00:00', '--job-id', '1112', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp3kyavtzw']
[2023-07-20T14:17:34.547+0000] {standard_task_runner.py:85} INFO - Job 1112: Subtask extract
[2023-07-20T14:17:34.587+0000] {task_command.py:410} INFO - Running <TaskInstance: my-first-dag.extract scheduled__2023-07-17T00:00:00+00:00 [running]> on host 70d871733d27
[2023-07-20T14:17:34.645+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ramesh@somemail.com' AIRFLOW_CTX_DAG_OWNER='Ramesh Sannareddy' AIRFLOW_CTX_DAG_ID='my-first-dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-17T00:00:00+00:00'
[2023-07-20T14:17:34.647+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-20T14:17:34.648+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cut -d":" -f1,3,6 /etc/passwd > /home/project/***/dags/extracted-data.txt']
[2023-07-20T14:17:34.659+0000] {subprocess.py:86} INFO - Output:
[2023-07-20T14:17:34.661+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /home/project/***/dags/extracted-data.txt: No such file or directory
[2023-07-20T14:17:34.662+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-20T14:17:34.673+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-20T14:17:34.675+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my-first-dag, task_id=extract, execution_date=20230717T000000, start_date=20230720T141734, end_date=20230720T141734
[2023-07-20T14:17:34.684+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1112 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 126)
[2023-07-20T14:17:34.719+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-20T14:17:34.737+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
